.PHONY: clean docs help quality requirements selfcheck upgrade

.DEFAULT_GOAL := help

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

upgrade: ## update python dependencies
	uv run --with edx-lint edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

docs: ## validate RST files
	doc8 README.rst CHANGELOG.rst

quality: ## check coding style with pycodestyle and pylint
	pylint repo_tools_data_schema
	pycodestyle repo_tools_data_schema
	isort --check-only --diff repo_tools_data_schema
	make selfcheck

requirements: ## install development environment requirements
	uv sync --group dev

test: ## run the few tests we have
	pytest

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."
